### ISSUE TITLE
Problem with calibration.

### ISSUE THREAD

**Issue by ismsanmar** [Coraye/Windows-Releases#1]
When I start a measurement, of any kind, the second step (calibration) is not carried out in any of my two spectrophotometers. When I press the calibration button on the program, it keeps the indicator continuously rotating. The lateral indicator light on the Colormunki does not even come on, or the halogen lamp on the i1 Pro. Of course I am using the argyllcms driver.

On the other hand, auto update system works correctly.

![Anotación 2019-08-30 165357](https://user-images.githubusercontent.com/560609/64031481-ca157b00-cb48-11e9-95b3-94af4b7ac787.png)
![Anotación 2019-08-30 170111](https://user-images.githubusercontent.com/560609/64031492-cda90200-cb48-11e9-8537-526d75d44473.png)

**Comment by ismsanmar** [comment]
I forgot to comment, these are my devices:
X-Rite Eye-one Pro Rev. D
X-Rite Colormunki Design

**Comment by Calderis** [comment]
Thank you, I'll check this out. I'll try to fix for the next release (should be 1.9.11)
